### ISSUE TITLE
Flag Myanmar is missing

### ISSUE THREAD

**Issue by cl3mcg** [gromain/openmoji-awesome#1]
The flag for Myanmar is missing from the list of countries.
No CDN link related to Myanmar Flag.

**Comment by gromain** [comment]
Hi,

I'm just back from a while at sea, I'll have a look at your issue tonight! Thanks for the heads up!

**Comment by gromain** [comment]
Now available with the class "oma-flag-myanmar-burma" at https://github.com/gromain/openmoji-awesome/blob/master/openmoji-color-awesome.css#L8918
